"""`ak alias` — shell shortcuts for ak, and the guarded shell rc block.

    ak alias [list]
    ak alias add <name> <kind> [@profile] [--ask | --auto]
    ak alias rm <name>
    ak alias preset classic [--on | --off]
    ak alias rc [--install | --remove | --print]

Definitions live in ~/.config/agentkit/aliases.json; `ak alias` renders
them into ~/.local/share/agentkit/aliases.sh as shell functions that call
this kit's `ak` by absolute path, and makes sure the user's shell rc
sources that file through one guarded block:

    # >>> agentkit >>>
    …PATH for the installed bin/ and `. aliases.sh`…
    # <<< agentkit <<<

The block is replaced in place (never duplicated) and removed cleanly.
The `classic` preset recreates the predecessor kit's wrapper names as plain
shortcuts for `ak <kind>` (autonomy follows the user's posture: the default,
or --ask / AGENTKIT_PERMISSIONS=ask); it ships off. POSIX shells only (bash, zsh, sh).
"""

import json
import os
import re
import sys

import common
from common import AkError, EXIT_USAGE

CLASSIC = [("claudex", "claude"), ("codexx", "codex"), ("cursorx", "cursor"), ("opencodex", "opencode"),
           ("pix", "pi"), ("clinex", "cline"), ("grokx", "grok")]
BEGIN = "# >>> agentkit >>>"
END = "# <<< agentkit <<<"
# POSIX sh function names: dash (often /bin/sh) rejects "-".
_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,31}$")
# Names an alias may never take: the kit itself and the CLIs it launches.
RESERVED = {"ak", "agentkit", "claude", "codex", "agent", "cursor-agent", "opencode", "pi", "cline", "grok",
            "herdr", "cd", "ls", "rm", "sh", "bash", "zsh", "env", "sudo", "git", "python3"}


def config_file():
    return os.path.join(os.path.dirname(common.env_file()), "aliases.json")


def script_file():
    return os.path.join(common.data_dir(), "aliases.sh")


def load():
    """{"classic": bool, "custom": [{"name", "kind", "profile", "auto"}]}; a
    missing or unreadable file is the default state."""
    try:
        with open(config_file()) as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return {"classic": False, "custom": []}
    if not isinstance(data, dict):
        return {"classic": False, "custom": []}
    # Re-validated on read: names become shell function names in aliases.sh.
    custom = [a for a in data.get("custom", []) if isinstance(a, dict) and isinstance(a.get("name"), str)
              and _NAME.match(a["name"]) and a["name"] not in RESERVED and isinstance(a.get("kind"), str)
              and re.match(r"^[a-z]+(-[a-z]+)?$", a["kind"])
              and (a.get("profile") is None or re.match(r"^@[a-z0-9._-]{1,32}$", str(a.get("profile"))))]
    return {"classic": data.get("classic") is True, "custom": custom}


def _write(path, text, mode=0o644):
    parent = os.path.dirname(path)
    if not os.path.isdir(parent):
        old = os.umask(0o077)
        try:
            os.makedirs(parent)
        finally:
            os.umask(old)
    import tempfile
    path = os.path.realpath(path)  # through a symlink (dotfiles), never replacing it
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), prefix="." + os.path.basename(path) + ".")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(text)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _sh_quote(value):
    return "'" + value.replace("'", "'\\''") + "'"


def render(state):
    ak = os.path.join(common.KIT_ROOT, "bin", "ak")
    lines = ["# Generated by `ak alias`; edit with `ak alias …`, not by hand.",
             "# Each alias is a function that calls ak by absolute path."]
    names = set()
    if state["classic"]:
        lines.append("# classic preset (ak alias preset classic --off to remove)")
        for name, kind in CLASSIC:
            names.add(name)
            lines.append("%s() { %s %s \"$@\"; }" % (name, _sh_quote(ak), kind))
    for alias in state["custom"]:
        if alias["name"] in names:
            continue
        words = [alias["kind"]]
        if alias.get("profile"):
            words.append(alias["profile"])
        if alias.get("ask"):
            words.append("--ask")
        elif alias.get("auto"):
            words.append("--auto")
        lines.append("%s() { %s %s \"$@\"; }" % (alias["name"], _sh_quote(ak), " ".join(_sh_quote(w) for w in words)))
    return "\n".join(lines) + "\n"


def save(state):
    _write(config_file(), json.dumps(state, indent=2, sort_keys=True) + "\n", 0o600)
    _write(script_file(), render(state))


# -------------------------------------------------------------- rc block

def rc_files(env):
    """The rc files the block belongs in: each existing ~/.zshrc / ~/.bashrc,
    plus the one for $SHELL; ~/.profile when there is neither."""
    home = env.get("HOME") or common.home()
    shell = os.path.basename(env.get("SHELL", ""))
    out = []
    for name, sh in ((".zshrc", "zsh"), (".bashrc", "bash")):
        path = os.path.join(home, name)
        if os.path.isfile(path) or shell == sh:
            out.append(path)
    if not out:
        out.append(os.path.join(home, ".profile"))
    return out


def block():
    bindir = os.path.join(common.data_dir(), "bin")
    script = script_file()
    return "\n".join([
        BEGIN,
        "# Managed by coding-agents-kit (install.sh, ak alias). Edit outside this block.",
        'if [ -d %s ]; then case ":$PATH:" in *:%s:*) ;; *) PATH=%s:"$PATH"; export PATH ;; esac; fi'
        % (_sh_quote(bindir), _sh_quote(bindir), _sh_quote(bindir)),
        "[ -f %s ] && . %s" % (_sh_quote(script), _sh_quote(script)),
        END,
    ]) + "\n"


def _split_block(text):
    """(before, after) around an existing block, or None when there is none."""
    lines = text.splitlines(True)
    begin = next((i for i, l in enumerate(lines) if l.rstrip("\n") == BEGIN), None)
    if begin is None:
        return None
    end = next((i for i in range(begin + 1, len(lines)) if lines[i].rstrip("\n") == END), None)
    if end is None:
        return None
    return "".join(lines[:begin]), "".join(lines[end + 1:])


def rc_install(env):
    """Add the block to each rc file, or replace it in place. Idempotent."""
    changed = []
    for path in rc_files(env):
        current = ""
        if os.path.isfile(path):
            with open(path) as handle:
                current = handle.read()
        parts = _split_block(current)
        if parts is not None:
            new = parts[0] + block() + parts[1]
        else:
            base = current if not current or current.endswith("\n") else current + "\n"
            new = base + ("\n" if base.strip() else "") + block()
        if new != current:
            mode = os.stat(path).st_mode & 0o777 if os.path.exists(path) else 0o644
            _write(path, new, mode)
            changed.append(path)
    return changed


def rc_remove(env):
    """Remove the block (and the blank line rc_install put before it)."""
    changed = []
    home = env.get("HOME") or common.home()
    for name in (".zshrc", ".bashrc", ".bash_profile", ".profile"):
        path = os.path.join(home, name)
        if not os.path.isfile(path):
            continue
        with open(path) as handle:
            current = handle.read()
        parts = _split_block(current)
        if parts is None:
            continue
        before, after = parts
        if before.endswith("\n\n"):
            before = before[:-1]
        _write(path, before + after, os.stat(path).st_mode & 0o777)
        changed.append(path)
    return changed


# ------------------------------------------------------------------ verbs

def _ensure_rc(env, quiet=False):
    # AGENTKIT_NO_RC=1, or an install made with --no-rc: never edit an rc.
    if env.get("AGENTKIT_NO_RC") == "1" or os.path.exists(os.path.join(common.data_dir(), ".no-rc")):
        return
    for path in rc_install(env):
        if not quiet:
            common.warn("updated %s (open a new shell, or: . %s)" % (path, path))


def _posture(alias):
    return "--ask" if alias.get("ask") else "--auto" if alias.get("auto") else ""


def cmd_list(state):
    print("classic preset: %s" % ("on" if state["classic"] else "off (ak alias preset classic --on)"))
    if state["classic"]:
        for name, kind in CLASSIC:
            print("  %-12s ak %s" % (name, kind))
    if state["custom"]:
        print("custom:")
        for a in state["custom"]:
            print("  %-12s ak %s" % (a["name"], " ".join(w for w in (a["kind"], a.get("profile") or "",
                                                                    _posture(a)) if w)))
    elif not state["classic"]:
        print("(no custom aliases — ak alias add <name> <kind> [@profile] [--ask | --auto])")
    return 0


def cmd_add(model, state, args, env):
    if len(args) < 2:
        raise AkError("usage: ak alias add <name> <kind> [@profile] [--ask | --auto]", EXIT_USAGE)
    name, kind = args[0], args[1]
    profile = None
    auto = False
    ask = False
    for extra in args[2:]:
        if extra == "--auto":
            auto = True
        elif extra == "--ask":
            ask = True
        elif extra.startswith("@") and profile is None:
            import profiles
            normalized = profiles.normalize(extra[1:])
            profile = "@" + normalized if normalized else None
        else:
            raise AkError("usage: ak alias add <name> <kind> [@profile] [--ask | --auto]", EXIT_USAGE)
    if auto and ask:
        raise AkError("--ask and --auto contradict each other; pass one", EXIT_USAGE)
    if not _NAME.match(name):
        raise AkError("'%s' is not an alias name: 1-32 letters, digits or '_', not starting with a digit"
                      % name, EXIT_USAGE)
    if name in RESERVED:
        raise AkError("refusing to define '%s': it would shadow a command ak relies on" % name, EXIT_USAGE)
    if kind not in model.kinds:
        raise AkError("unknown kind '%s'. Kinds: %s" % (kind, " ".join(model.kind_names())), EXIT_USAGE)
    if state["classic"] and name in dict(CLASSIC):
        raise AkError("'%s' belongs to the classic preset, which is on" % name, EXIT_USAGE)
    replaced = any(a["name"] == name for a in state["custom"])
    state["custom"] = [a for a in state["custom"] if a["name"] != name]
    state["custom"].append({"name": name, "kind": kind, "profile": profile, "auto": auto, "ask": ask})
    state["custom"].sort(key=lambda a: a["name"])
    save(state)
    _ensure_rc(env)
    print("%s %s -> ak %s" % ("replaced" if replaced else "added", name,
                              " ".join(w for w in (kind, profile or "", "--ask" if ask else "--auto" if auto else "") if w)))
    return 0


def cmd_rm(state, args, env):
    if len(args) != 1:
        raise AkError("usage: ak alias rm <name>", EXIT_USAGE)
    if not any(a["name"] == args[0] for a in state["custom"]):
        raise AkError("no custom alias named '%s'" % args[0], common.EXIT_NOT_READY)
    state["custom"] = [a for a in state["custom"] if a["name"] != args[0]]
    save(state)
    print("removed %s (open a new shell, or: unset -f %s)" % (args[0], args[0]))
    return 0


def cmd_preset(state, args, env):
    if not args or args[0] != "classic" or len(args) > 2 or (len(args) == 2 and args[1] not in ("--on", "--off")):
        raise AkError("usage: ak alias preset classic [--on | --off]", EXIT_USAGE)
    if len(args) == 1:
        print("classic preset: %s" % ("on" if state["classic"] else "off"))
        return 0
    on = args[1] == "--on"
    if on:
        clash = [a["name"] for a in state["custom"] if a["name"] in dict(CLASSIC)]
        if clash:
            raise AkError("custom aliases use classic names (%s); remove them first" % ", ".join(clash), EXIT_USAGE)
    state["classic"] = on
    save(state)
    if on:
        _ensure_rc(env)
        print("classic preset on: %s (each is ak <kind>; autonomy follows your posture)"
              % " ".join(n for n, _ in CLASSIC))
    else:
        print("classic preset off (open a new shell, or: unset -f %s)" % " ".join(n for n, _ in CLASSIC))
    return 0


def cmd_rc(args, env):
    if args == ["--install"]:
        for path in rc_install(env):
            print("updated %s" % path)
        if not os.path.exists(script_file()):
            save(load())
        return 0
    if args == ["--remove"]:
        for path in rc_remove(env):
            print("removed the agentkit block from %s" % path)
        return 0
    if args in ([], ["--print"]):
        sys.stdout.write(block())
        return 0
    raise AkError("usage: ak alias rc [--install | --remove | --print]", EXIT_USAGE)


def main(model, args, env):
    sub = args[0] if args else "list"
    rest = args[1:]
    state = load()
    if sub in ("list", "ls"):
        return cmd_list(state)
    if sub == "add":
        return cmd_add(model, state, rest, env)
    if sub in ("rm", "remove"):
        return cmd_rm(state, rest, env)
    if sub == "preset":
        return cmd_preset(state, rest, env)
    if sub == "rc":
        return cmd_rc(rest, env)
    raise AkError("unknown alias command '%s'. Use: list | add <name> <kind> [@profile] [--ask | --auto] | rm <name> | "
                  "preset classic [--on|--off] | rc [--install|--remove|--print]" % sub, EXIT_USAGE)
