"""Provider config writers: Codex overlays, OpenCode providers, Pi models.

Rules every writer keeps (ported from coding-agents-setup-kit, hardened):
  * the secret never lands on disk: Codex gets `env_key = "<VAR>"`,
    OpenCode `{env:<VAR>}`, Pi `"$<VAR>"` — the CLI reads the value from
    its environment at run time;
  * merge-safe: OpenCode and Pi files are shared with the user's own setup,
    so only the one provider entry is replaced and everything else is kept;
    a file that does not parse, or whose shape is unexpected, is refused
    and left byte-identical;
  * a Codex overlay is the kit's own file: one without the kit's header is
    the user's, and is refused instead of overwritten;
  * one-time backup (<file>.agentkit.bak) before the first change, atomic
    replace, files created mode 600 inside directories created mode 700.
"""

import json
import os
import tempfile

from kinds import expand_home

HEADER = "# Generated by coding-agents-kit (ak); do not hand-edit."
# Overlays written by the kit this one replaces are also ours to rewrite.
KNOWN_HEADERS = (HEADER, "# Generated by coding-agents-setup-kit; do not hand-edit.")


class WriterError(Exception):
    pass


def _ensure_dir(path):
    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        old = os.umask(0o077)
        try:
            os.makedirs(parent)
        finally:
            os.umask(old)


def _atomic_write(path, text):
    _ensure_dir(path)
    mode = None
    if os.path.exists(path):
        mode = os.stat(path).st_mode & 0o777
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path) or ".", prefix="." + os.path.basename(path) + ".",
                               suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(text)
        os.chmod(tmp, mode if mode is not None else 0o600)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def _backup_once(path):
    backup = path + ".agentkit.bak"
    if os.path.exists(path) and not os.path.exists(backup):
        with open(path, "rb") as src:
            data = src.read()
        fd = os.open(backup, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "wb") as dst:
            dst.write(data)


def _load_json_object(path, env_hint):
    if not os.path.exists(path):
        return {}
    with open(path) as handle:
        raw = handle.read()
    if not raw.strip():
        return {}
    try:
        data = json.loads(raw)
    except ValueError as exc:
        raise WriterError("refusing to modify %s: not valid JSON (%s). Fix it by hand%s and retry."
                          % (path, exc, env_hint))
    if not isinstance(data, dict):
        raise WriterError("refusing to modify %s: the top level is not an object." % path)
    return data


def _toml_string(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def write_codex(path, provider_id, name, base_url, env_key, model):
    """A Codex profile overlay (`codex -p <name>` reads <name>.config.toml)."""
    if os.path.exists(path):
        with open(path) as handle:
            first = handle.readline().rstrip("\n")
        if first not in KNOWN_HEADERS:
            raise WriterError("refusing to overwrite %s: it was not written by coding-agents-kit "
                              "(no generated header). Move it aside and retry." % path)
    if not provider_id.replace("-", "").replace("_", "").isalnum():
        raise WriterError("bad provider id %r" % provider_id)
    text = "\n".join([
        HEADER,
        "model = %s" % _toml_string(model),
        "model_provider = %s" % _toml_string(provider_id),
        "[model_providers.%s]" % provider_id,
        "name = %s" % _toml_string(name),
        "base_url = %s" % _toml_string(base_url),
        "env_key = %s" % _toml_string(env_key),
        'wire_api = "responses"',
        "",
    ])
    if os.path.exists(path):
        with open(path) as handle:
            if handle.read() == text:
                return False
    _atomic_write(path, text)
    return True


def write_opencode(path, provider_id, env_key, base_url, models):
    """Merge ONE provider into opencode.json; never touches the global model."""
    data = _load_json_object(path, " (or point OPENCODE_CONFIG at another file)")
    providers = data.setdefault("provider", {})
    if not isinstance(providers, dict):
        raise WriterError("refusing to modify %s: 'provider' is not an object." % path)
    vision = {"attachment": True, "modalities": {"input": ["text", "image"], "output": ["text"]}}
    whitelist = []
    model_map = {}
    for mid in models:
        if mid and mid not in whitelist:
            whitelist.append(mid)
            entry = {"id": mid, "name": mid}
            entry.update(vision)
            model_map[mid] = entry
    existing = providers.get(provider_id)
    existing = existing if isinstance(existing, dict) else {}
    options = existing.get("options")
    options = dict(options) if isinstance(options, dict) else {}
    options.update({"apiKey": "{env:%s}" % env_key, "baseURL": base_url})
    merged = dict(existing)
    merged.update({"options": options, "whitelist": whitelist, "models": model_map})
    if providers.get(provider_id) == merged:
        return False
    providers[provider_id] = merged
    _backup_once(path)
    _atomic_write(path, json.dumps(data, indent=2) + "\n")
    return True


def write_pi(path, provider_id, base_url, env_key, context_window, max_tokens, reasoning_effort, specs):
    """Upsert ONE provider into Pi's models.json (apiKey is "$<VAR>")."""
    data = _load_json_object(path, "")
    providers = data.setdefault("providers", {})
    if not isinstance(providers, dict):
        raise WriterError("refusing to modify %s: 'providers' is not an object." % path)
    models = []
    seen = set()
    for spec in specs:
        mid, _, label = spec.partition(":")
        if not mid or mid in seen:
            continue
        seen.add(mid)
        models.append({
            "id": mid,
            "name": "%s (%s)" % (mid, label) if label else mid,
            "reasoning": True,
            "input": ["text", "image"],
            "contextWindow": int(context_window),
            "maxTokens": int(max_tokens),
        })
    entry = {
        "baseUrl": base_url,
        "api": "openai-completions",
        "apiKey": "$%s" % env_key,
        "compat": {"supportsDeveloperRole": False, "supportsReasoningEffort": bool(reasoning_effort)},
        "models": models,
    }
    if providers.get(provider_id) == entry:
        return False
    providers[provider_id] = entry
    _backup_once(path)
    _atomic_write(path, json.dumps(data, indent=2) + "\n")
    return True


def apply(kind, ctx):
    """Run the kind's writer (if any) with templates expanded in ctx.
    Returns the written path or None. Never receives the secret."""
    spec = kind.data.get("writer")
    if not spec:
        return None
    env_key = kind.key_var
    target = spec["file"]
    if ":" in target and not target.startswith("{") and target.split(":", 1)[0] in kind.cli["roots"]:
        path = ctx.ref_path(target)
    else:
        path = ctx.expand(target)
    path = expand_home(path, ctx.home)
    wtype = spec["type"]
    if wtype == "codex":
        write_codex(path, spec["provider_id"], spec["name"], ctx.expand(spec["base_url"]), env_key,
                    ctx.expand(spec["model"]))
    elif wtype == "opencode":
        write_opencode(path, spec["provider_id"], env_key, ctx.expand(spec["base_url"]),
                       [ctx.expand(m) for m in spec["models"]])
    elif wtype == "pi":
        write_pi(path, spec["provider_id"], ctx.expand(spec["base_url"]), env_key,
                 spec["context_window"], spec["max_tokens"], spec["reasoning_effort"],
                 [ctx.expand(m) for m in spec["models"]])
    return path
